inicio modulo 13
LucasGuimaDev/ExerciciosEBAC pull request #1
Opened 2023-09-14 02:13 UTC by LucasGuimaDev

2023-09-14 02:15 UTC, dtleal commented
Por favor, descreva o que será feito neste módulo. Talvez seja uma boa idéia criar uma pasta especifica para cada módulo também.

2023-09-14 02:23 UTC, dtleal approved these changes

2023-09-14 02:23 UTC, dtleal commented on README.md
> +## Módulo 13
O que será feito aqui?

2023-09-14 02:24 UTC, LucasGuimaDev commented on README.md
> +## Módulo 13
aqui vai o desenvolvimento do modulo 13

2023-09-14 02:27 UTC, dtleal requested changes
Aguardando desenvolvimento do modulo.

2023-09-14 02:28 UTC, LucasGuimaDev commented
@dtleal irei iniciar o desenvolvimento do modulo e solicitar o seu review

2023-09-25 21:21 UTC, dtleal commented
@LucasGuimaDev como este PR foi só um teste, sugiro duas opções:
1. converte este PR para draft até que ele esteja de fato disponivel para review
2. delete este PR, uma vez que nao temos alteracoes para subir em dev

2023-10-09 20:49 UTC, dtleal approved these changes

2023-10-09 20:50 UTC, dtleal commented
Aprovando visto que nao tem tanto problema

2023-10-09 20:51 UTC, dtleal approved these changes

2023-10-31 22:13 UTC, closed without merging